### ISSUE TITLE
feat: 리차징룸 예약 관련 기능 구현

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#105]
## Description

지점의 리차징룸 및 예약 가능 시간 보여주는 API와
리차징룸 id, 시간 받아서 리차징룸을 예약하는 API 필요

## Tasks(Process)

- [x] 리차징룸 리스트 API
- [x] 리차징룸 예약 API
- [x] 리차징룸 중복 검증 API
