### ISSUE TITLE
bug: 1차 테스트 예약 관련 버그 목록

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#135]
## Description
1차 테스트에서 나온 예약 관련 버그 목록

## Tasks(Process)

- [x] 당일 예약만 가능해야 하는데 23:30 분 이후 다음날 예약이 가능함 
-> (30분 전 -> 30분 30분후 00분)으로 변환하는 과정에서 생긴 오류
- [x] 홍대1호점에서 받아온 시간대를 클릭하고 예약하기 하면 예약 성공되고 다시 홍대1호점 리차징룸 가보면 해당 시간대 canReserve:false로 정상 작동해서 클릭 불가. 나의 예약 리스트에서 해당 강남1호점 리차징룸 예약 취소하면 예약 취소까지 잘 되는데 해당 시간대 canReserve:false로 남아있음 
-> 예약 가능 불가능 판정할 때 취소된 예약을 걸러내지 않아 생긴 버그
- [x] 가끔씩 리차징룸 리스트가 500에러를 일으키며 불러와지지 않는 현상 
-> 리차징룸에서 예약 가능 시간을 판별할 때 Reservation을 가져올 때 RechargingRoom 관련 예약이 아닌 예약도 불러와 생긴 버그
- [x] 리차징룸이 여러개일 때 리차징룸2를 예약하면 정상 예약이 됐다고 뜨지만, 다시 돌아가보면 해당 리차징룸2의 시간대 canReserve:true로 되어있음, 
예약 내역 리스트에는 정상적으로 예약까지 된거 확인, 예약 취소도 정상작동
-> 3번째 버그와 같은 이유로 생긴 버그
- [x] 07.06 02:00~04:00 으로 미팅룸 예약 잡고 취소 하면 예약은 취소되지만, 같은 시간대에 다시 해당 인원 예약하려고 하면 이미 예약이 있다고 선택 불가
-> 예약 가능 인원 조회에서 인원의 예약을 취소되지 않은것까지 불러와서 생긴 버그
- [x] 예약 가능한 시간에도 토스트 메세지가 출력되고 예약이 되지 않는 문제가 있습니다. 8:30~9:00 예약 존재시 9:00부터 예약이 가능해야 하는데 가까운 시간대에서 문제가 발생합니다.
-> 예약 검증을 할 때 겹치는 부분에서 querydsl의 between을 쓰기 위해 >= 가 아닌 > 을 써야 할때는 나노세컨드 단위로 더하고 뺀걸 비교했는데 나노세컨드 단위의 경우 적용되지 않는 현상으로 세컨드로 바꿈
- [x] 미팅룸 예약 후 해당 시간 리차징룸 예약이 가능합니다.
- [x] 미팅룸 예약할 때, toastType이 null이면 중복된 예약이 없어서 예약 상세페이지로 넘어갈 수 있는데, 예약 상세페이지에서 예약버튼 클릭하면 저렇게 중복된 예약이 있다고 뜸 당일 예약확인해도 없음
