### ISSUE TITLE
refactor: fail Response에 커스텀 코드 추가

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#14]
## Description

기존 Response에 String errorCode 필드가 추가된다.

이 이유는 다음과 같다.

1. 프로젝트 부피가 커지고 예외 상황이 많아질 수록 단순 HTTP 상태 코드로 예외 상황을 구분짓기 애매하다고 느끼는 경우가 많아짐
2. HTTP 상태 코드로만 구분을 짓더라도 Backend 에서 애매하다고 느낀 부분을 Frontend에서도 똑같이 느끼게 되면 결국에는 프론트와의 협의를 통해 A 상황은 400코드 B 상황은 404 코드 이런식으로 따로 얘기를 해야 되는 상황이 발생
3. 이런 상황 때문에 HTTP 상태 코드는 원칙대로 지키되 fail Response에 컨벤션이 명확히 정해진 Custom Code를 같이 보내고 이를 문서화하여 프론트와 공유하고 프론트는 Custom Code 를 기준으로 예외 상황을 구분하여 그 상황마다 맞는 로직으로 처리하기로 결정

Custom Code의 컨벤션은 아래와 같다.
- Custom Code의 구조는 숫자-숫자 의 구조이다. (예: 0-001)
- 첫 숫자는 도메인의 구분을 위함이고 이는 프론트와 공유하는 Custom Code 명세서 컨벤션 아래에 기술했다.
- 뒤의 숫자는 001부터 시작해 1씩 증가하는 형태이며 코드를 추가할 땐 명세서의 해당 도메인 마지막 숫자에서 1을 더하고 생성 즉시 명세서에 추가한다.
- 한번 정해진 Custom Code는 불가피한 상황이 아니면 절대로 수정해선 안되며 수정하게 될 경우 백엔드, 프론트엔드 모든 팀원에게 상황을 공유해야 한다.

## Tasks(Process)

- [x] Response Record 에 String errorCode 필드 추가
- [x] ExceptionHandler 에서도 errorCode 추가 로직 구현
- [x] Interface ErrorCode 에 String getCustomCode 추가
