### ISSUE TITLE
feat: 회원가입 기능 구현

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#2]
## Description
기획이 끝나기 전이라 전체적인 프로젝트 설계에 앞서
회원 관련 기능들 우선 설계 후 구현

![image](https://github.com/4bujak-4bujak/backend/assets/121492369/b5dae7df-44d8-4c48-948c-8b0db8d04e1b)
해당 회원가입 기능 구현

## Tasks(Process)

- [x] 회원 관련 API 명세서
- [x] 회원 table, 계약된 기업 table 설계 (회원가입에 쓸 용도로 우선 간단하게)
- [x] 회원가입 기능 구현
- [x] 전화번호 인증 기능 구현
- [x] 이메일 인증 기능 구현
