### ISSUE TITLE
feat: 회원 관련 추가 api 들 구현

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#23]
## Description
회사 + 실명을 나타내는 api
회원에 이미지가 추가되어 관련 api 들 수정

## Tasks(Process)
- [x] 회사 + 실명을 나타내는 api 구현
- [x] 회원 가입 할 때 기본 이미지로 가입되게 수정
- [x] 회원 정보 및 프로필 수정 api 구현
