### ISSUE TITLE
feat: 지도 관련 api 구현

### ISSUE THREAD

**Issue by KimSangwoo1259** [4bujak-4bujak/backend#28]
## Description

단건조회, 전체조회 api 설계 및 데이터 생성
## Tasks(Process)

- [x] 단건조회 api 구현
- [x] 전체조회 api 구현
- [x] 위도, 경도를 포함한 branch data 생성
