### ISSUE TITLE
feat: 예약관련 Entity 설계

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#31]
## Description
예약과 관련된 Entity 를 생성

## Tasks(Process)
- [x] 회원 - 예약 간 다대다
- [x] 공간 관련 Entity 리팩토링
- [x] 공간 - 예약 관련 일대다
