### ISSUE TITLE
feat: 미팅룸 예약 관련 나머지 api 구현

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#61]
## Description
기존 구현한 미팅룸 리스트 반환 api 를 제외 
필요한 나머지 api 들 구현

## Tasks(Process)

- [ ] 미팅룸 예약 과정중 초대 가능 멤버 조회 api
- [ ] 미팅룸 상세 조회 api 
- [ ] 미팅룸 예약 api
