### ISSUE TITLE
feat: 포커스존 예약 관련 기능 구현

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#62]
## Description

프론트 측에서 포커스존 구현을 미팅룸보다 우선시 해달라는 요구가 있어
포커스존 관련 API 를 먼저 구현

## Tasks(Process)
- [x] 지점의 현재 이용 가능한 좌석수 보여주는 API
- [x] 지점의 좌석 배치도에서 좌석 관련 list 보여주는 API
- [x] 좌석을 예약하는 API
- [x] 좌석 이용 종료 API
- [x] 자정에 모든 좌석 이용 종료로 바꾸는 스케줄된 메소드 필요
