### ISSUE TITLE
feat: 일정명 기능 추가

### ISSUE THREAD

**Issue by zoomin3022** [4bujak-4bujak/backend#69]
## Description
![image](https://github.com/4bujak-4bujak/backend/assets/121492369/2a42c73b-5d59-46a4-9e5e-822375f35d58)
일정명이 필요

일정명은 다음과 같음
미팅룸의 경우 예약 당사자가 설정한 이름을 따라가고 수정은 불가능
포커스존과 리차징룸은 예약 진행 시 일정 이름 기본값에서 수정이 불가능
포커스존 : 포커스존 / 리차징룸 : 리차징룸

## Tasks(Process)

- [x] Reservation Entity 에 reservationName 추가
- [x] 예약을 할 때 미팅룸의 경우 일정명을 받음
- [x] 예약을 할 때 포커스존, 리차징룸의 경우 고정된 기본값을 이름으로 가짐
